version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    ports:
      - '3306:3306'
    environment:
      
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=root_ClickBeard
      - MARIADB_DATABASE=ClickBeard
  codeigniter:
    image: docker.io/bitnami/codeigniter:4
    ports:
      - '8000:8000'
    environment:
      
      - ALLOW_EMPTY_PASSWORD=yes
      - CODEIGNITER_DATABASE_HOST=mariadb
      - CODEIGNITER_DATABASE_PORT_NUMBER=3306
      - CODEIGNITER_DATABASE_USER=root_ClickBeard
      - CODEIGNITER_DATABASE_NAME=ClickBeard
    volumes:
      - './ClickBeard:/app'
    depends_on:
      - mariadb
